[project]
name = "django-apiary"
version = "0.1.0"
description = "Typed API views for Django."
readme = "README.md"
authors = [
    { name = "Dan Watson", email = "dcwatson@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Intended Audience :: Developers",
]
requires-python = ">=3.12"
dependencies = [
    "msgspec>=0.21.1",
]

[project.scripts]
apiary = "apiary:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "django>=6.0",
]

[tool.uv.build-backend]
module-name = "apiary"
